import CreatorLayout from "@/components/layout/CreatorLayout";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  HelpCircle, 
  Video, 
  DollarSign, 
  Upload, 
  User, 
  Trophy,
  CreditCard,
  MessageSquare,
  Package,
  AlertCircle
} from "lucide-react";

const faqCategories = [
  {
    title: "Getting Started",
    icon: User,
    color: "bg-primary/10 text-primary",
    questions: [
      {
        q: "How do I set up my account?",
        a: "After receiving your invite link, create your account with your email and password. Then complete your profile by adding your name and connecting your Stripe account for payouts. You'll also want to review the brand guidelines in the 'Brand' section before submitting videos.",
      },
      {
        q: "How do I connect my bank account for payouts?",
        a: "Go to your Profile page and click 'Connect Stripe Account'. You'll be guided through Stripe's secure onboarding process to link your bank account. This is required to receive any earnings from your videos.",
      },
      {
        q: "What commission rate do I earn?",
        a: "Your commission rate is displayed on your dashboard. Rates vary by creator and can be found in your profile. Higher-tier creators may earn increased commission rates based on performance.",
      },
    ],
  },
  {
    title: "Video Submissions",
    icon: Upload,
    color: "bg-success/10 text-success",
    questions: [
      {
        q: "How do I submit a video?",
        a: "Click the 'Submit Video' button in the sidebar or on your dashboard. You can upload multiple videos at once. Each video will be given a unique ID and submitted for review.",
      },
      {
        q: "What video formats are accepted?",
        a: "We accept most common video formats including MP4, MOV, and WebM. Videos should be in 9:16 portrait format (TikTok/Reels style) for best results.",
      },
      {
        q: "How long does review take?",
        a: "Most videos are reviewed within 24-48 hours. You'll receive a notification when your video is approved or if revisions are needed.",
      },
      {
        q: "Why was my video rejected?",
        a: "Videos may be rejected if they don't follow brand guidelines, have quality issues, or don't align with the current campaign brief. Check your video details for specific feedback and the 'Briefs' section for current requirements.",
      },
    ],
  },
  {
    title: "Earnings & Payouts",
    icon: DollarSign,
    color: "bg-info/10 text-info",
    questions: [
      {
        q: "How do I earn money?",
        a: "You earn a commission on the revenue generated by your approved videos when they run as ads. The better your videos perform (views, clicks, sales), the more you earn.",
      },
      {
        q: "What is the $500 Monthly Guarantee?",
        a: "Creators who submit 35 or more approved videos in a calendar month are guaranteed at least $500 in earnings for that month. Track your progress on the dashboard.",
      },
      {
        q: "When do I get paid?",
        a: "Payouts are processed on the 1st of each month for the previous month's earnings. You must have a connected Stripe account and meet the minimum payout threshold.",
      },
      {
        q: "What is the minimum payout threshold?",
        a: "The minimum payout amount is set by the platform administrator. Any earnings below this threshold will roll over to the next month.",
      },
    ],
  },
  {
    title: "Performance & Analytics",
    icon: Trophy,
    color: "bg-warning/10 text-warning",
    questions: [
      {
        q: "How do I track my video performance?",
        a: "Visit the 'Analytics' section to see detailed performance metrics for your videos including impressions, clicks, and sales. The dashboard also shows your top-performing content.",
      },
      {
        q: "What is ROAS?",
        a: "ROAS stands for Return on Ad Spend. It measures how much revenue your video generated compared to how much was spent on advertising it. Higher ROAS means better performance.",
      },
      {
        q: "How do I improve my tier?",
        a: "Your tier (Bronze, Silver, Gold, Platinum) is based on your number of approved videos. Keep submitting quality content that gets approved to level up!",
      },
    ],
  },
  {
    title: "Bounties & Bonuses",
    icon: Package,
    color: "bg-accent/10 text-accent",
    questions: [
      {
        q: "What are bounties?",
        a: "Bounties are special challenges with bonus rewards. Complete specific milestones (like reaching a sales target) within the timeframe to earn extra money on top of your regular earnings.",
      },
      {
        q: "How do I claim a bounty reward?",
        a: "When you meet a bounty's requirements, it's automatically tracked. Once verified, the bounty payout will be added to your next monthly payout.",
      },
    ],
  },
  {
    title: "Samples",
    icon: Package,
    color: "bg-secondary/80 text-secondary-foreground",
    questions: [
      {
        q: "How do I request product samples?",
        a: "Go to the 'Samples' section and submit a request with the product you need and your shipping address. Sample requests are reviewed by the admin team.",
      },
      {
        q: "How long do samples take to arrive?",
        a: "Sample delivery times vary. You can track the status of your request in the Samples section. Once shipped, you'll see tracking information if provided.",
      },
    ],
  },
];

export default function CreatorHelp() {
  const navigate = useNavigate();

  return (
    <CreatorLayout>
      <div className="space-y-4 md:space-y-6">
        {/* Header */}
        <div>
          <h1 className="text-lg md:text-2xl font-bold flex items-center gap-2">
            <HelpCircle className="w-5 h-5 md:w-6 md:h-6" />
            Help Center
          </h1>
          <p className="text-xs md:text-sm text-muted-foreground hidden md:block">
            Find answers to common questions about using the platform
          </p>
        </div>

        {/* Quick Contact */}
        <Card className="border-accent/20 bg-accent/5 cursor-pointer hover:bg-accent/10 transition-colors" onClick={() => navigate("/creator/chat")}>
          <CardContent className="flex items-center gap-3 md:gap-4 py-3 md:py-4 px-3 md:px-6">
            <div className="p-1.5 md:p-2 rounded-lg bg-accent/10 shrink-0">
              <MessageSquare className="w-4 h-4 md:w-5 md:h-5 text-accent" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="font-medium text-sm md:text-base">Need more help?</p>
              <p className="text-[10px] md:text-sm text-muted-foreground truncate">
                Contact your admin through Chat for support.
              </p>
            </div>
            <Button size="sm" className="shrink-0 text-[10px] md:text-xs">
              <MessageSquare className="w-3 h-3 mr-1" /> Chat Now
            </Button>
          </CardContent>
        </Card>

        {/* FAQ Categories */}
        <div className="space-y-3 md:space-y-6">
          {faqCategories.map((category) => (
            <Card key={category.title}>
              <CardHeader className="p-3 md:p-6 pb-2 md:pb-3">
                <CardTitle className="flex items-center gap-2 md:gap-3 text-sm md:text-lg">
                  <div className={`p-1.5 md:p-2 rounded-lg ${category.color}`}>
                    <category.icon className="w-4 h-4 md:w-5 md:h-5" />
                  </div>
                  {category.title}
                </CardTitle>
              </CardHeader>
              <CardContent className="p-3 pt-0 md:p-6 md:pt-0">
                <Accordion type="single" collapsible className="w-full">
                  {category.questions.map((item, index) => (
                    <AccordionItem key={index} value={`${category.title}-${index}`}>
                      <AccordionTrigger className="text-left hover:no-underline text-xs md:text-base py-2 md:py-4">
                        {item.q}
                      </AccordionTrigger>
                      <AccordionContent className="text-xs md:text-sm text-muted-foreground leading-relaxed">
                        {item.a}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Still Need Help */}
        <Card className="border-muted">
          <CardContent className="py-6 md:py-8 text-center">
            <AlertCircle className="w-10 h-10 md:w-12 md:h-12 text-muted-foreground mx-auto mb-3 md:mb-4" />
            <h3 className="font-semibold mb-2 text-sm md:text-base">Still have questions?</h3>
            <p className="text-[10px] md:text-sm text-muted-foreground max-w-md mx-auto px-4">
              If you couldn't find the answer you were looking for, reach out to your admin 
              through the Chat section. They're happy to help!
            </p>
          </CardContent>
        </Card>
      </div>
    </CreatorLayout>
  );
}
